# -*- coding: utf-8 -*-
"""final_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gN7OUVBSiuzMUv_csOkK8OtrBURyC_9B
"""

# version 8: selecting 10 articles related to a main wikipedia article in the first hop and expanding all links in the second hop

# importing python packages

import requests
import os
import json
from datetime import datetime
import time
import networkx as nx
import matplotlib.pyplot as plt
import numpy as np

# requirements to use wiki API
headers = {"User-Agent": "WikiNetworkProject/8.0"}

# defining functions

# removing non-articles links from the links extracted

def filter_links(links):
    ignore_prefixes = ("Help:", "File:", "Category:", "Special:", "Talk:")
    filtered = []

    for link in links:
        if not link.startswith(ignore_prefixes):
            filtered.append(link)

    return filtered




# finding revision id's of previous revisions for the main article
def yearly_revisions(title, years):
    url = "https://en.wikipedia.org/w/api.php"

    revisions = []

    # getting the current revision id
    params = {"action": "query", "titles": title, "rvlimit": 1, "prop": "revisions", "rvprop": "ids|timestamp", "format": "json"}

    r = requests.get(url, params=params, headers=headers)
    data = r.json()
    pages = data['query']['pages']

    for page in pages.values():
        revs = page.get("revisions", [])
        if revs:
            revisions.append(revs[0])

    # finding revision id closest to June 30th of previous years of the main article
    current_year = datetime.utcnow().year

    for i in range(1, years + 1):
        year = current_year - i
        target_time = f"{year}-06-30T00:00:00Z"

        params["rvstart"] = target_time
        params["rvdir"] = "older"

        r = requests.get(url, params=params, headers=headers)
        data = r.json()
        pages = data["query"]["pages"]

        for page in pages.values():
            revs = page.get("revisions", [])
            if revs:
                revisions.append(revs[0])

    return revisions


# finding closest revision id for linked articles wrt main article's revision id (for getting time consistent temporal graphs)
def closest_revision(title, target_timestamp):
    url = "https://en.wikipedia.org/w/api.php"

    params = {"action": "query", "titles": title, "rvlimit": 1, "rvprop": "ids|timestamp", "rvstart": target_timestamp, "rvdir": "older", "prop": "revisions", "format": "json"}

    r = requests.get(url, params=params, headers=headers)
    data = r.json()
    pages = data['query']['pages']

    for page in pages.values():
        revs = page.get("revisions", [])
        if revs:
            return revs[0]

    return None


# extracting all links in an article for a given revision id
def links_from_revision(rev_id):
    url = "https://en.wikipedia.org/w/api.php"

    params = {"action": "parse", "oldid": rev_id, "prop": "links", "format": "json"}

    r = requests.get(url, params=params, headers=headers)
    data = r.json()

    # to avoid errors, only using parsed data
    if "parse" in data:
        return filter_links([l["*"] for l in data["parse"]["links"] if l["ns"] == 0])

    return []


# imputting articles related to the main wikipedia page, separated by commas
def first_hop(selected_articles):
    articles = [a.strip() for a in selected_articles.split(",") if a.strip()]
    return articles



# building a temporal graph of the wikipedia articles and internal links
def temporal_graph(main_page, first_hop_nodes, years=5):

    graphs = {}

    # finding yearly revision ids for main article
    revisions = yearly_revisions(main_page, years)

    for root_rev in revisions:

        timestamp = root_rev["timestamp"]
        year = timestamp[:4] #:4 for extracting the year

        # building a directed graph
        G = nx.DiGraph()

        for node in first_hop_nodes:
            G.add_edge(main_page, node)

        for node in first_hop_nodes:

            # finding revision id closest to parent revision id
            child_rev = closest_revision(node, timestamp)
            if not child_rev:
                continue

            child_id = child_rev["revid"]

            # extracting all outgoing links (second hop)
            links_lvl2 = links_from_revision(child_id)

            for link in links_lvl2:
                G.add_edge(node, link)

        graphs[year] = G

    return graphs

# creating adjacency lists for each timepoint

def adjacency_lists(graphs):
    adj_lists = {}

    for year, G in graphs.items():
        adj_list = {}

        for u, v in G.edges():
            if u not in adj_list:
                adj_list[u] = []

            adj_list[u].append(v)

        adj_lists[year] = adj_list

    return adj_lists



# creating edge lists for each timepoint

def edge_lists(graphs):
    edge_lists = {}

    for year, G in graphs.items():
        edge_lists[year] = list(G.edges())

    return edge_lists


# creating adjacency matrix fore ach timepoint

def adjacency_matrices(graphs):
    matrices = {}

    for year, G in graphs.items():
        nodes = list(G.nodes())
        node_index = {node: i for i, node in enumerate(nodes)}

        matrix = np.zeros((len(nodes), len(nodes)))

        for u, v in G.edges():
            i = node_index[u]
            j = node_index[v]

            matrix[i][j] = 1

        matrices[year] = {"matrix": matrix, "nodes": nodes}

    return matrices

# chosen main wikipedia page - COVID-19
main_page = "COVID-19"

# chosen related articles (10)
input_articles = "Symptoms of COVID-19, Contagious disease, SARS-CoV-2, Coronavirus, World Health Organization, COVID-19 pandemic, COVID-19 testing, COVID-19 vaccine, Coronavirus diseases, Transmission of COVID-19"
first_hop_nodes = first_hop(input_articles)
graphs = temporal_graph(main_page, first_hop_nodes, years=10)


adj_lists = adjacency_lists(graphs)
adj_matrices = adjacency_matrices(graphs)
edge_lists = edge_lists(graphs)


# saving outputs

# saving outputs

# adjacency list
with open("adj_lists.json", "w") as f:
    json.dump(adj_lists, f, indent=2)

# edge list
with open("edge_lists.json", "w") as f:
    json.dump(edge_lists, f, indent=2)

# gexf file 
for year, G in graphs.items():
    nx.write_gexf(G, f"COVID_19_{year}.gexf")

# adjacency matrix
for year, data in adj_matrices.items():
    matrix = data["matrix"]
    nodes = data["nodes"]

    np.save(f"adj_matrix_{year}.npy", matrix)
    np.savetxt(f"adj_matrix_{year}.csv", matrix, delimiter=",")

    with open(f"nodes_{year}.json", "w") as f:
        json.dump(nodes, f)

# sparse matrix 
for year, data in adj_matrices.items():
    matrix = data["matrix"]

    sparse_matrix = csr_matrix(matrix)
    save_npz(f"adj_matrix_{year}_sparse.npz", sparse_matrix)

# printing number of nodes and edges for each timepoint
for year, G in graphs.items():
    print(f"{year}: nodes={len(G.nodes())}, edges={len(G.edges())}")

print ()
  
# adjacency list
print("adj_lists.json:", os.path.getsize("adj_lists.json"), "bytes")

# edge list
print("edge_lists.json:", os.path.getsize("edge_lists.json"), "bytes")

# matrix files
for year in adj_matrices:
    dense_file = f"adj_matrix_{year}.npy"
    sparse_file = f"adj_matrix_{year}_sparse.npz"

    if os.path.exists(dense_file):
        print(f"{dense_file}:", os.path.getsize(dense_file), "bytes")

    if os.path.exists(sparse_file):
        print(f"{sparse_file}:", os.path.getsize(sparse_file), "bytes")
