# -*- coding: utf-8 -*-
"""Test_Code_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/106f0mTq_iRwNQ7SW2CHiDI0UMrGub1hJ
"""

import requests
import json
import networkx as nx
import matplotlib.pyplot as plt

# requirements to use wiki API
headers = {"User-Agent": "WikiNetworkProject/1.0"}

# defining functions
# modification to previous version -- using closest revision id to parent id for link expansion for layers >2

def filter_links(links):
    bad_prefixes = ("Help:", "File:", "Category:", "Special:", "Talk:")
    return [l for l in links if not l.startswith(bad_prefixes)]

def get_top_revisions(title, limit=5):
    url = "https://en.wikipedia.org/w/api.php"
    params = {
        "action": "query",
        "titles": title,
        "rvlimit": limit,
        "prop": "revisions",
        "rvprop": "ids|timestamp",
        "format": "json"
    }

    r = requests.get(url, params=params, headers=headers).json()
    pages = r['query']['pages']

    for page in pages.values():
        return page.get("revisions", [])

    return []

def get_latest_revision(title):
    url = "https://en.wikipedia.org/w/api.php"
    params = {
        "action": "query",
        "titles": title,
        "rvlimit": 1,
        "prop": "revisions",
        "rvprop": "ids|timestamp",
        "format": "json"
    }

    r = requests.get(url, params=params, headers=headers).json()
    pages = r['query']['pages']

    for page in pages.values():
        revs = page.get("revisions", [])
        if revs:
            return revs[0]

    return None


def get_closest_revision(title, target_timestamp):
    url = "https://en.wikipedia.org/w/api.php"
    params = {
        "action": "query",
        "titles": title,
        "rvlimit": 10,
        "rvprop": "ids|timestamp",
        "rvstart": target_timestamp,
        "rvdir": "older",
        "prop": "revisions",
        "format": "json"
    }

    r = requests.get(url, params=params, headers=headers).json()
    pages = r['query']['pages']

    for page in pages.values():
        revs = page.get("revisions", [])
        if revs:
            return revs[0]

    return None


def get_links_from_revision(rev_id, max_links):
    url = "https://en.wikipedia.org/w/api.php"
    params = {
        "action": "parse",
        "oldid": rev_id,
        "prop": "links",
        "format": "json"
    }

    r = requests.get(url, params=params, headers=headers).json()

    links = []
    if "parse" in r and "links" in r["parse"]:
        links = [l["*"] for l in r["parse"]["links"] if l["ns"] == 0]

    links = filter_links(links)
    return links[:max_links]



def build_time_consistent_multi_rev(page, max_links=5, num_revs=3):

    result = {page: []}

    root_revs = get_top_revisions(page, limit=num_revs)
    if not root_revs:
        return result

    for root_rev in root_revs:

        root_id = root_rev["revid"]
        root_time = root_rev["timestamp"]

        rev_block = {
            "rev_id": root_id,
            "timestamp": root_time,
            "links": {}
        }

        # ---- Hop 1 ----
        links_lvl1 = get_links_from_revision(root_id, max_links)

        for link in links_lvl1:
            child_rev = get_closest_revision(link, root_time)
            if not child_rev:
                continue

            child_id = child_rev["revid"]
            child_time = child_rev["timestamp"]

            rev_block["links"][link] = {
                "rev_id": child_id,
                "timestamp": child_time,
                "links": []
            }

            # ---- Hop 2 ----
            links_lvl2 = get_links_from_revision(child_id, max_links)
            rev_block["links"][link]["links"] = links_lvl2

        result[page].append(rev_block)

    return result

data = build_time_consistent_multi_rev(
    "SARS-CoV-2",
    max_links=5,
    num_revs=3
)

import json
print(json.dumps(data, indent=2))

G = nx.DiGraph()

for parent, revisions in data.items():

    for rev_block in revisions:
        root_id = rev_block["rev_id"]

        # Optional: distinguish nodes by revision
        parent_node = f"{parent} ({root_id})"

        for child, cdata in rev_block["links"].items():
            child_id = cdata["rev_id"]
            child_node = f"{child} ({child_id})"

            # Edge: parent → child
            G.add_edge(parent_node, child_node)

            # Hop 2
            for sub in cdata["links"]:
                sub_node = sub  # no revision stored for hop 2
                G.add_edge(child_node, sub_node)


print("Nodes:", G.number_of_nodes())
print("Edges:", G.number_of_edges())

plt.figure(figsize=(12, 10))
nx.draw(G, with_labels=True, node_size=50, font_size = 10)
plt.show()