# -*- coding: utf-8 -*-
"""Covid 19_vaccines.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jXwg265Lx7owUHwDtnOucTpKWBqVeH4f
"""

# Step 1: Article Discovery — COVID-19 Vaccines
# Run this script first to identify your article set before building the graph.

import requests
import time
import pandas as pd
import os

# ── Output directory ──────────────────────────
output_dir = '/content/drive/MyDrive/DSP_Project_Data'
os.makedirs(output_dir, exist_ok=True)
os.makedirs('../data', exist_ok=True)

# ── Wikimedia session ─────────────────────────
SESSION = requests.Session()
SESSION.headers.update({
    'User-Agent': 'DSP-Project-COVID19/1.0 (aadya.ashwin@students.iiserpune.ac.in) Python/requests'
})

url = 'https://en.wikipedia.org/w/api.php'


# ─────────────────────────────────────────────
# HELPER 1: Get articles directly inside a category
# ─────────────────────────────────────────────
def get_category_members(category, limit=500):
    """Fetch all article titles from a Wikipedia category (pages only)."""
    articles = []
    cmcontinue = None

    while True:
        params = {
            'action':  'query',
            'list':    'categorymembers',
            'cmtitle': f'Category:{category}',
            'cmlimit': 'max',
            'cmtype':  'page',       # articles only, not subcategories
            'format':  'json'
        }
        if cmcontinue:
            params['cmcontinue'] = cmcontinue

        r = SESSION.get(url, params=params, timeout=10).json()
        for member in r.get('query', {}).get('categorymembers', []):
            articles.append(member['title'])

        if 'continue' in r and len(articles) < limit:
            cmcontinue = r['continue']['cmcontinue']
        else:
            break
        time.sleep(0.3)

    return articles


# ─────────────────────────────────────────────
# HELPER 2: Get subcategories inside a category
# ─────────────────────────────────────────────
def get_subcategories(category):
    """Fetch all subcategory names inside a Wikipedia category."""
    url = 'https://en.wikipedia.org/w/api.php'
    params = {
        'action':  'query',
        'list':    'categorymembers',
        'cmtitle': f'Category:{category}',
        'cmtype':  'subcat',         # subcategories only
        'cmlimit': 100,
        'format':  'json'
    }
    r = SESSION.get(url, params=params, timeout=10).json()
    # Strip the "Category:" prefix for reuse in get_category_members()
    return [
        m['title'].replace('Category:', '')
        for m in r.get('query', {}).get('categorymembers', [])
    ]


# ══════════════════════════════════════════════
# MAIN: Discover articles for COVID-19 VACCINES
# ══════════════════════════════════════════════

print("=" * 55)
print("  Step 1: Wikipedia Article Discovery")
print("  Domain: COVID-19 | Sub-topic: Vaccines")
print("=" * 55)

# ── Verified top-level categories (confirmed on Wikipedia) ──
# Category:COVID-19 vaccines
#   ├── COVID-19 vaccines by country        (~74 articles)
#   ├── Deployment of COVID-19 vaccines     (~4  articles)
#   ├── COVID-19 vaccine misinformation...  (~50 articles)
#   ├── COVID-19 vaccine producers          (~41 articles)
#   └── COVID-19 vaccine stubs              (~49 articles)

ROOT_CATEGORY = 'COVID-19 vaccines'

print(f"\n[1/3] Fetching subcategories under '{ROOT_CATEGORY}'...")
subcategories = get_subcategories(ROOT_CATEGORY)
print(f"  Found {len(subcategories)} subcategories:")
for s in subcategories:
    print(f"    - {s}")

# ── Collect articles from root + all subcategories ──
print(f"\n[2/3] Fetching articles from root category and all subcategories...")
category_articles = set()

# Root category articles
members = get_category_members(ROOT_CATEGORY)
category_articles.update(members)
print(f"  'Category:{ROOT_CATEGORY}': {len(members)} articles")

# Subcategory articles
for subcat in subcategories:
    members = get_category_members(subcat)
    category_articles.update(members)
    print(f"  'Category:{subcat}': {len(members)} articles")
    time.sleep(0.2)

print(f"\n  >> Total (before filtering): {len(category_articles)} articles")

# ── Filter out non-article namespaces ──────────
print("\n[3/3] Filtering irrelevant pages...")
EXCLUDE_KEYWORDS = [
    'Wikipedia:', 'Template:', 'Help:', 'File:', 'Portal:',
    'Talk:', 'User:', 'List of', 'Draft:', 'Module:'
]
filtered = [
    a for a in category_articles
    if not any(a.startswith(kw) for kw in EXCLUDE_KEYWORDS)
]

# ── Summary ────────────────────────────────────
print(f"\n{'='*55}")
print(f"  DISCOVERY SUMMARY")
print(f"{'='*55}")
print(f"  Root category:      {ROOT_CATEGORY}")
print(f"  Subcategories:      {len(subcategories)}")
print(f"  Total (raw):        {len(category_articles)}")
print(f"  After filtering:    {len(filtered)}")

# ── Save ───────────────────────────────────────
df = pd.DataFrame({'article': sorted(filtered)})
output_path = os.path.join(output_dir, 'discovered_articles_vaccines.csv')
df.to_csv(output_path, index=False)
print(f"\n  Saved {len(df)} articles to: {output_path}")

print(f"\nSample articles discovered:")
print(df.head(20).to_string(index=False))

url = "https://en.wikipedia.org/w/api.php"
HEADERS = {"User-Agent": "MyWikiBot/1.0 (aadya.ashwin@students.iiserpune.ac.in)"}
def get_internal_links(article_title):
    links = []
    params = {
        "action": "query",
        "titles": article_title,
        "prop": "links",
        "pllimit": "max",
        "plnamespace": 0,
        "format": "json"
    }

    while True:
        response = requests.get(url, params=params, headers=HEADERS)

        if response.status_code != 200 or not response.text.strip():
            print(f"Bad response for '{article_title}': {response.status_code}")
            break

        data = response.json()
        pages = data["query"]["pages"]

        for page_id, page_data in pages.items():
            if page_id == "-1":
                print(f"Article not found: {article_title}")
                break
            for link in page_data.get("links", []):
                links.append(link["title"])

        if "continue" in data:
            params["plcontinue"] = data["continue"]["plcontinue"]
        else:
            break

        time.sleep(0.5)

    return links


internal_links = {}
for article in filtered:
    raw_links = get_internal_links(article)
    filtered_links = [link for link in raw_links if link in filtered and link != article]
    for links in filtered_links:
        internal_links[article] = filtered_links

import json

with open('/content/drive/MyDrive/DSP_Project_Data/links.json', 'w') as f:
    json.dump(internal_links, f)

import networkx as nx

def build_graph(link_map):
    """
    Build a directed graph from the link map.
    Edge A → B means: Article A contains a hyperlink to Article B
    """
    G = nx.DiGraph()  # Directed graph

    for article in filtered :
        G.add_node(article)

    for article, linked_articles in link_map.items() :
        for target in linked_articles:
            G.add_edge(article, target)

    return G

with open("/content/drive/MyDrive/DSP_Project_Data/links.json", "r") as f:
    link_map = json.load(f)

G = build_graph(link_map)

print(f"Nodes (articles): {G.number_of_nodes()}")
print(f"Edges (links): {G.number_of_edges()}")

def compute_metrics(G):
    """Compute key graph metrics for every node."""

    in_degree = dict(G.in_degree())

    out_degree = dict(G.out_degree())

    pagerank = nx.pagerank(G, alpha=0.85)

    # Betweenness centrality = how often this article is a "bridge"
    # NOTE: This is slow for large graphs, sample if needed
    if G.number_of_nodes() < 500:
        betweenness = nx.betweenness_centrality(G)
    else:
        betweenness = nx.betweenness_centrality(G, k=100)  # approximate

    # Build results dataframe
    df = pd.DataFrame({
        "article": list(G.nodes()),
        "in_degree": [in_degree[n] for n in G.nodes()],
        "out_degree": [out_degree[n] for n in G.nodes()],
        "pagerank": [pagerank[n] for n in G.nodes()],
        "betweenness": [betweenness[n] for n in G.nodes()]
    })

    df = df.sort_values("pagerank", ascending=False)
    return df

metrics_df = compute_metrics(G)
print("\nTop 10 Most Important Articles (by PageRank):")
print(metrics_df.head(10).to_string(index=False))