# -*- coding: utf-8 -*-
"""dashboard_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hLri2iC6eUTHSBw7M2QO6Su14m7sYisj
"""

"""
Dashboard for Wikipedia knowledge flow and link structure
"""


import json
import os
import streamlit as st     # to build the UI
import networkx as nx     # to build graphs
import plotly.graph_objects as go     # go is graph objects
import plotly.express as px
import pandas as pd


# ─────────────────────────────────────────────

# page configuration
st.set_page_config(
    page_title="Wikipedia Knowledge Flow",
    layout="wide",
    initial_sidebar_state="expanded"
)


# ─────────────────────────────────────────────

# to load the data
@st.cache_resource     # saves objects created
def load_snapshots():

  snapshots={}
  years=["list of all years"]     # need to be added

  for year in years:
    filename=f"graph_{year}.gexf"
    if os.path.exists(filename):
      snapshots[year] = nx.read_gexf(filename)     # file in gexf format
    else:
      st.warning(f"file not found: {filename}")
  return snapshots


# to get node metrics
@st.cache_data
def compute_metrics(_G):     # the underscore allows for mutability

  pagerank = nx.pagerank(_G, alpha=0.85)     # alpha is the damping factor, page rank tells you which nodes are linked by other imp nodes
  in_degree = dict(_G.in_degree())
  out_degree = dict(_G.out_degree())

  if _G.number_of_nodes > 200:   # if-else statement helps in saving time
    betweenness = nx.betweenness_centrality(_G, k=100, normalize=True)
  else:
    betweenness = nx.betweenness_centrality(_G, normalized=True)

  nodes = _G.nodes()
  df = pd.DataFrame({
      "article": list(_G.nodes()),
      "pagerank": [pagerank.get(n, 0) for n in nodes],
      "in_degree": [in_degree.get(n, 0) for n in nodes],
      "out_degree": [out_degree.get(n, 0) for n in nodes]
      "betweenness": [betweenness.get(n, 0) for n in nodes]
  }).sort_values("pagerank", ascending=False).reset_index(drop=True)

  return df, _G


# ─────────────────────────────────────────────

# network visualisation
def build_networks(G, metrics_df, top_n=40):

  # defining important data
  top_nodes=metrics_df.head(top_n)["article"].tolist()
  subgraph=G.subgraph(top_nodes)
  pos = nx.spring_layout(subgraph, k=2.5, seed=42)     # spring layout allows for node layout based on connectivity, k controls ideal dist between nodes, seed allows for same graph each time
  pagerank = dict(zip(metrics_df["article"], metrics_df["pagerank"]))
  in_degree = dict(zip(metrics_df["article"], metrics_df["in_degree"]))

  # edges
  edge_x = []     # can be considered the 'coordinate' of x
  edge_y = []
  for u, v in subgraph.edges():
    x1, x2 = pos[u]
    y1, y2 = pos[v]
    edge_x += [x1, x2, None]     # 'none' allows for connection of only x1 and x2
    edge_y += [y1, y2, None]

  # the edge coordinates are joint by a line
  edge_scatter = go.Scatter(
      x=edge_x, y=edge_y,
      mode="lines",
      line=dict(width=0.6, color="#30363d"),
      hoverinfo="none"
  )


  # nodes
  nodes = subgraph.nodes()
  node_x = [pos[n][0] for n in nodes]
  node_y = [pos[n][1] for n in nodes]
  node_sizes = [max(8, pagerank.get(n, 0)*3000) for n in nodes]     # size is a scaled up measure of page rank, with a least count
  node_colors = [in_degree.get(n, 0) for n in nodes]
  node_text = [
      f"<b>{n}<b><br>Pagerank: {pagerank.get(n, 0):.4f}<br>In-degree: {in_degree.get(n, 0)}"     # <b> is to make bold
      for n in nodes
  ]

  node_scatter = go.Scatter(
      x=node_x, y=node_y,
      mode="markers+text",
      hoverinfo="text",
      text=[n if pagerank.get(n, 0) > metrics_df["pagerank"].quanitile(0.75) else "" for n in subgraph.nodes()],     # top 25th percentile's text is seen
      textposition="top center",
      textfont=dict(size=8, color="#e6edf3"),
      marker=dict(
          size=node_sizes,
          color=node_colors,
          colorscale="YlOrRd",
          showscale=True,
          colorbar=dict(
              title="In-degree",
              titlefont=dict(color="#8b949e"),
              tickfont=dict(color="#8b949e"),
              bgcolor="#161b22",
              bordercolor="#30363d"
          ),
          line=dict(width=1, color="#30363d")
      )
  )

  fig = go.Figure(
      data=[edge_scatter, node_scatter],
      layout=go.Layout(
          paper_bgcolor="#0d1117",
          plot_bgcolor="#0d1117",
          showlegend=False,
          hovermode="closest",
          margin=dict(b=0, l=0, r=0, t=0),
          xaxis=dict(showgrid=False, zeroline=False, showticklabels=False),
          yaxis=dict(showgrid=False, zeroline=False showticklabels=False),
          height=550
      )
  )
  return fig


# ─────────────────────────────────────────────

# centrality over time chart
def build_centrality_chart(snapshots, metric="pagerank", top_n=10):

    all_data = []

    for year, _G in snapshots.items():
        df, _G = compute_metrics(_G)
        top = df.head(top_n)[["article", metric]].copy()     # copy allows one to make actually make a ___ rather than just view
        top["year"] = year
        all_data.append(top)

    combined = pd.concat(all_data)     # concat appends

    # to only keep articles that appear in all years
    all_years = list(snapshots.keys())
    appearances = combined.groupby("article")["year"].nunique()
    stable_articles = appearances[appearances == len(all_years)].index
    combined = combined[combined["article"].isin(stable_articles)]

    fig = px.line(
        combined,
        x="year", y="metric",
        color="article",
        markers=True,
        template="plotly_dark",
        labels={metric:metric_replace("_", " ").title()},
        color_discrete_sequence=px.colors.qualitative.Set2
    )
    fig.update_traces(line=dict(width=2), marker=dict(size=9))
    return fig


# ─────────────────────────────────────────────

# link changes chart
def compute_link_changes(snapshots):

    years = sorted(snapshots.keys())
    records = []

    for i in range(len(years) - 1):     # -1 is to account for 0 counting
        y1 = years[i]
        y2 = years[i + 1]
        s1 = snapshots[y1]
        s2 = snapshots[y2]

        all_articles = set(s1.keys()) | set(s2.keys())     # union of the sets
        total_added = total_removed = 0
        article_changes = []

        for article in all_articles:
            links_before = set(s1.get(article, []))
            links_after = set(s2.get(article, []))
            added = links_after - links_before
            removed = links_before - links_after

            total_added += len(added)
            total_removed += len(removed)

            if added or removed:
                article_changes.append({
                    "article": article,
                    "added": list(added),
                    "removed": list(removed),
                    "net": len(added) - len(removed)
                })
        records.append({
            "period": f"{y1} → {y2}"
            "links_added": total_added,
            "links_removed": total_removed,
            "net_change": total_added - total_removed,
            "article_changes": sorted(article_changes, key=lambda x: len(x["added"]) + len(x["removed"]), reverse=True)     # lambda x: len(x["added"]) + len(x["removed"])
        })

    return records

def build_changes_chart(change_records):

    periods = [r["period"] for r in change_records]
    added = [r["links_added"] for r in change_records]
    removed = [-r["links_removed"] for r in change_records]

    fig = go.Figure()
    fig.add_trace(go.Bar(     # creates bar chart
        name="Added", x=periods, y=added,
        marker_color="#3fb950", text=added, textposition="outside",
        textfont=dict(color="#3fb950")
    ))
    fig.add_trace(go.Bar(
        name="Removed", x=periods, y=removed,
        marker_color="#f85149", text=[abs(r) for r in removed], textposition="outside",
        textfont=dict(color="#f85149")
    ))
    fig.update_layout(
        barmode="overlay",
        paper_bgcolor="#0d1117",
        plot_bgcolor="#161b22",
        xaxis = dict(gridcolor="#30363d", color="#8b949e"),     # metrics saved as dictionaries
        yaxis=dict(gridcolor="#30363d", color="#8b949e", title="Number of Links"),
        legend=dict(bgcolor="#161b22", bordercolor="#30363d"),     # plotly needs configurations in dictionaries
        height=350,
        margin=dict(t=20)
    )

    return fig


# ─────────────────────────────────────────────

# to create the UI
def main():
  # header
  # st.markdown is like a print statement, below is in html script for customized markdown
  st.markdown("""
  <div style='padding: 20px 0 0'>
      <h1 style='font-family: Space Mono, monospace:
          Wikipedia Knowledge Flow
      </h>
      <p style='color: #8b949e; margin: 6px 0 0 0; font-size: 0.95rem'>
          Link Structure & Network Analysis Dashboard
      </p>
  </div>
  """, unsafe_allow_html=True)     # 'true' states that its safe to run

  # to load data
  with st.spinner("loading snapshot data..."):
    snapshot=load_snapshots()

  if not snapshots:
    st.error("No snapshot JSON files found. Make sure JSON files are in the same directory.")
    return

  available_years = sorted(snapshots.key())     # creates a list in ascending order

  # creating the sidebar
  with st.sidebar:
    st.markdown("### Controls")     # '###' is to define size of text
    selcted_year=st.select_slider(
        "Select Year",
        options=available_years
        value=available_years[-1]     # -1 is get the slider from oldest to newest
    )
    top_n_network=st.slider("Nodes in Network Graph", 10, 800, 400, 5)     # lower limit, upper limit, default, step size
    top_n_table = st.slider("Articles in Rankings Table", 5,30,10,5)
    top_n_lines=st.slider("Articles in Centrality Chart",3,15,8,1)
    metric_choice = st.selectbox(
        "Centrality Metric",
        ["pagerank","in_degree","betweenness"]     # betweeness measures how often a node occurs on the shortest path between two nodes
        format_func=lambda x: x.replace("_"," ").title()     # replace underscore with face
    )

    st.markdown("---")
    st.markdown("### Loaded Snapshots")
    for y in available_years:
      n_articles = snapshots[y].number_of_nodes()
      n_edges = snapshots[y].number_of_edges()
      st.markdown(f"**{y}** - {n_articles} articles, {n_edges:,} edges")     # asterisk for formating

  # computing metrics for year that is selected
  G = snapshots[selected_year]
  metrics_df, G = compute_metrics(G)

  # top metrics
  st.markdown(f",div class = 'section-header'> Network Overview - {selected_year}</div", unsafe_allow_html=True)

  c1,c2,c3,c4 = st.columns(4)
  with c1:
    st.metric("Articles (Nodes)", f"{G.number_of_nodes():,}")
  with c2:
    st.metric("Links (Edges)", f"{G.number_of_edges():,}")
  with c3:
    density = nx.density(G)
    st.metric("Network Density", f"{density:.4f}")
  with C4:
    top_article=metrics_df.iloc[0]["articles"]     # iloc is used to pick a specific column
    st.metric("Top Hub", top_article[:25] + "..." if len(top_article) > 25 else top_article)

  # building the network graph
  st.markdown(f"<div class='section-header'> Network Graph - Top {top_n_network} Articles </div>", unsafe_allow_html=True)
  st.caption("Node size = PageRank importance · Node colour = In-degree · Hover for details")

  with st.spinner("Rending network..."):
    network_fig = build_plotly_network(G, metrics_df, top_n=top_n_network)
    st.plotly_chart(network_fig, use_container_width=True)

  # table for top articles and centrality chart
  col_left, col_right = st.columns([1,1])
  with col_left:
    st.markdown(f"<div class='section-header'> Top {top_n_table} Articles by {metric_choice.replace('_',' ').title()}</div>", unsafe_allow_html=True)
    display_df= metrics_df[["articles","pagerank",  "in_degree", "out_degree", "betweeness"]].head(top_n_table).copy()
    display_df["pagerank"]=display_df["pagerank"].apply(lambda x: f"{x:.4f}")
    display_df["betweenness"]=display_df["betweenness"].apply(lambda x: f"{x:.4f}")
    display_df.index = range(1, len(dispaly_df)+1)
    display_df.columns = ["Article", "PageRank", "In-Degree", "Out-Degree", " Betweeness"]
    st.dataframe(display_df, use_container_width=True, height=350)

  with col_right:
    st.markdown(f"<div class='section-header'> {metric_choice.replace('_',' ').title()} Over Time,/div>", unsafe_allow_html=True)
    centrality_fig = build_centraility_chart(snapshots, metric=metric_choice, top_n=top_n_lines)
    st.plotly_chart(centralitu_fig, use_container_width=True)

  # link changes
  st.markdown("<div class='section-header'> Link Changes Between Years</div>", unsafe_allow_html=True)

  change_records=compute_link_changes(snapshots)
  changes_fig = biold_changes_chart(change_records)
  st.plotly_chart(changes_fig, use_container_width=True)

  # for per article changes
  st.markdown("#### Per Article Changes")
  period_labels=[r["period"] for r in change_records]
  sel_perid=st.selectbox("Select Period", period_labels)
  sel_record = nect(r for r in change_records if r["period"] == sel_period)

  if sel_record["article_changes"]:
    for item in sel_record["article_changes"][:10]:
      with st.expander(f"{item['article']} (+{len(item['added'])} / -{len(item['removed'])})"):
        ca, cr = st.columns(2)
        with ca:
          st.markdown("**Added Links:**")
          for link in item["added"][:15]:
            st.markdown(f"<span class='added-link'>+{link}</span>", unsafe_allow_html=True)
        with cr:
          st.markdown("**Removed Links:**")
          for link in item["removed"][:15]:
            st.markdown(f"<span class='removed-link'>+{link}</span>", unsafe_allow_html=True)
    else:
      st.info("no linke changes found for this period.")

    # footer
    st.markdown("---")
    st.markdown(
        "<p style='text-align:centre; color:#8b949e; font-size:0.8rem'>DS3294 · Wikepedia Link Structure & Knowldedge Flow</p>",
        unsafe_allow_html=True
    )

if __name__ == "__main__":
  main()